version: "3.9"

services:
  campaign:
    build:
      context: services/campaign
    env_file:
      - ./services/campaign/.env
    container_name: campaign
    ports:
      - "8000:8000"
    networks:
      - "fundly-network"

  campaign_db:
    image: postgres:latest
    container_name: campaign_db
    env_file:
      - ./services/campaign/.env
    volumes:
      - "campaign-db-data:/var/lib/postgresql/data"
    expose:
      - "5432"
    networks:
      - "fundly-network"

volumes:
  campaign-db-data:

networks:
  fundly-network:
